services:
  app:
    container_name: test-app
    user: 1000:1000
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: test/phpfpm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - XDG_CONFIG_HOME=./
  web:
    image: nginx:1
    container_name: test-web
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx/
    ports:
      - "8080:80"

  db:
    container_name: test-db-container
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - "5432:5432"
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
         - ./docker_volumes/mysql:/var/lib/mysql
